version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8020:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3030:3000"
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
      - frontend_cache:/app/.cache
    environment:
      - REACT_APP_API_URL=http://localhost:8020
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  frontend_cache: